# Generated by Django 5.1.7 on 2025-11-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_otp_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
