# Generated by Django 5.1.7 on 2025-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('both', 'Both')], max_length=10, null=True),
        ),
    ]
