# Generated by Django 5.1.7 on 2025-03-26 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='product_images/')),
                ('product_vedio', models.FileField(blank=True, null=True, upload_to='product_vedios/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
