# Generated by Django 5.1.7 on 2025-04-19 20:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_product_farmer_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
