# Generated by Django 5.1.7 on 2025-04-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_marketplaceproduct_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplaceproduct',
            old_name='images',
            new_name='images_market',
        ),
    ]
