# Generated by Django 5.1.7 on 2025-04-21 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_negotiation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negotiation',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='user',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='negotiation_type',
            field=models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negotiations_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.negotiation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NegotiationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiation_type', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], max_length=10)),
                ('validity_hours', models.PositiveIntegerField(blank=True, help_text='Only for active type', null=True)),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Only for passive type', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.product_farmer')),
            ],
        ),
    ]
