# Generated by Django 5.1.7 on 2025-04-21 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_timestamp_negotiation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_negotiations', to=settings.AUTH_USER_MODEL),
        ),
    ]
