# Generated by Django 5.1.7 on 2025-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_negotiationmessage_proposed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
