# Generated by Django 5.1.7 on 2025-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_address_cart_cartitem_notification_order_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grains', 'Grains'), ('Spices', 'Spices'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Seeds', 'Seeds'), ('Machinery', 'Machinery'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=40),
        ),
    ]
