# Generated by Django 5.1.7 on 2025-04-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_cartitem_product_cartitem_product_farmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
