# Generated by Django 5.2.8 on 2025-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_admincatalogproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincatalogproduct',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admincatalogproduct',
            name='farmer_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admincatalogproduct',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admincatalogproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
