# Generated by Django 5.2.8 on 2025-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_admincatalogproduct_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincatalogproduct',
            name='offer_category',
            field=models.CharField(choices=[('none', 'Not an Offer'), ('flash_deal', 'Flash Deal'), ('seasonal', 'Seasonal Offer'), ('limited_stock', 'Limited Stock'), ('trending', 'Trending Now')], default='none', help_text='Select offer type to display in Top Offers section', max_length=20),
        ),
    ]
