# Generated by Django 5.2.8 on 2025-11-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_admincatalogproduct_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincatalogproduct',
            name='category',
            field=models.CharField(choices=[('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Tools', 'Tools'), ('Equipment', 'Equipment'), ('Irrigation', 'Irrigation'), ('Top Offers', 'Top Offers Only')], max_length=40),
        ),
    ]
