# Generated by Django 5.1.7 on 2025-08-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_logactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactivity',
            name='product_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.product_farmer'),
        ),
    ]
