# Generated by Django 5.1.7 on 2025-09-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_enable_pg_trgm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='accounts.product_farmer'),
            preserve_default=False,
        ),
    ]
