# Generated by Django 5.2.8 on 2025-11-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Grains', 'Grains'), ('Spices', 'Spices'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Oilseeds', 'Oilseeds'), ('Dry Fruits', 'Dry Fruits'), ('Organic Products', 'Organic Products'), ('Farm Animals', 'Farm Animals'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=40),
        ),
    ]
