# Generated by Django 5.1.7 on 2025-10-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_offer_product_type_offer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('organic', 'Organic Farming'), ('equipment', 'Modern Farming Equipment'), ('harvest', 'Seasonal Harvest Sale'), ('sustainable', 'Sustainable Farming Solutions')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_badge', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('page_slug', models.SlugField(unique=True)),
                ('related_category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('organic', 'Organic Products'), ('equipment', 'Farm Equipment'), ('harvest', 'Harvest Produce'), ('sustainable', 'Sustainable Tools')], max_length=20)),
            ],
        ),
    ]
